# Name: Ruhan Rafiq Bhaleshah
# Roll Number: PIAIC143499
# Batch: 7

In [1]:
#method 1
import numpy as ruhan
ruhan.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
#method 2
ruhan.add(2,5)

7

In [3]:
#method 3
ruhan.subtract(3,4)

-1

In [4]:
#method 4
ruhan.multiply(4,2)

8

In [5]:
#method 5
ruhan.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
#method 6
ruhan.zeros((2,4),dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
#method 7
ruhan.full((3,2),77)

array([[77, 77],
       [77, 77],
       [77, 77]])

In [8]:
#method 8
ruhan.arange(1,10,6)

array([1, 7])

In [9]:
#method 9
ruhan.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [10]:
#method 10
ruhan.random.random((1,2))

array([[0.10373397, 0.02735031]])

In [11]:
r=ruhan.eye(10)

In [14]:
#method 11
ruhan.shape(r)

(10, 10)

In [15]:
#method 12
ruhan.empty(5)

array([ 2.,  4.,  6.,  8., 10.])

In [16]:
#method 13
r=ruhan.random.randint(1,10,(5,5))
r

array([[7, 8, 4, 3, 9],
       [9, 5, 1, 2, 1],
       [1, 6, 5, 3, 6],
       [8, 5, 4, 4, 5],
       [7, 7, 7, 2, 4]])

In [18]:
#method 14
ruhan.size(r)

25

In [19]:
#method 15
r.dtype

dtype('int64')

In [20]:
#method 16
r.data

In [21]:
#method 17
r.itemsize

8

In [22]:
#method 18
r.ndim

2

In [23]:
#method 19
s=ruhan.random.default_rng(10)
s

Generator(PCG64) at 0x7F425D4846D8

In [24]:
#method 20
t=ruhan.random.randint(0,10,(3,3))
t

array([[3, 4, 4],
       [6, 5, 5],
       [9, 4, 5]])

In [25]:
#method 21
t.min()

3

In [26]:
#method 22
t.max()

9

In [27]:
#method 23
t.mean()

5.0

In [28]:
#method 24
t.sum()

45

In [29]:
#method 26
ruhan.exp(t)

array([[  20.08553692,   54.59815003,   54.59815003],
       [ 403.42879349,  148.4131591 ,  148.4131591 ],
       [8103.08392758,   54.59815003,  148.4131591 ]])

In [30]:
#method 27
ruhan.random.seed(1)
ruhan.random.random((5,5))

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02],
       [6.70467510e-01, 4.17304802e-01, 5.58689828e-01, 1.40386939e-01,
        1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01,
        8.76389152e-01]])

In [31]:
#method 28
t.ravel()

array([3, 4, 4, 6, 5, 5, 9, 4, 5])

In [32]:
#method 29
ruhan.abs(t)

array([[3, 4, 4],
       [6, 5, 5],
       [9, 4, 5]])

In [33]:
#method 30
ruhan.pi

3.141592653589793

In [34]:
#method 31
ruhan.sin(t)

array([[ 0.14112001, -0.7568025 , -0.7568025 ],
       [-0.2794155 , -0.95892427, -0.95892427],
       [ 0.41211849, -0.7568025 , -0.95892427]])

In [35]:
#method 32
ruhan.cos(t)

array([[-0.9899925 , -0.65364362, -0.65364362],
       [ 0.96017029,  0.28366219,  0.28366219],
       [-0.91113026, -0.65364362,  0.28366219]])

In [36]:
#method 33
ruhan.tan(t)

array([[-0.14254654,  1.15782128,  1.15782128],
       [-0.29100619, -3.38051501, -3.38051501],
       [-0.45231566,  1.15782128, -3.38051501]])

In [51]:
#method 34
ruhan.arcsin(0.10)

0.1001674211615598

In [52]:
#method 35
ruhan.arccos(0.10)

1.4706289056333368

In [53]:
#method 36
ruhan.arctan(0.10)

0.09966865249116204

In [54]:
#method 37
ruhan.log(t)

array([[1.09861229, 1.38629436, 1.38629436],
       [1.79175947, 1.60943791, 1.60943791],
       [2.19722458, 1.38629436, 1.60943791]])

In [55]:
#method 38
ruhan.log2(t)

array([[1.5849625 , 2.        , 2.        ],
       [2.5849625 , 2.32192809, 2.32192809],
       [3.169925  , 2.        , 2.32192809]])

In [56]:
#method 39
ruhan.log10(t)

array([[0.47712125, 0.60205999, 0.60205999],
       [0.77815125, 0.69897   , 0.69897   ],
       [0.95424251, 0.60205999, 0.69897   ]])

In [57]:
#method 40
ruhan.add.reduce(t)

array([18, 13, 14])

In [58]:
#method 41
ruhan.multiply.reduce(t)

array([162,  80, 100])

In [59]:
#method 42
ruhan.add.accumulate(t)

array([[ 3,  4,  4],
       [ 9,  9,  9],
       [18, 13, 14]])

In [60]:
#method 43
ruhan.multiply.accumulate(t)

array([[  3,   4,   4],
       [ 18,  20,  20],
       [162,  80, 100]])

In [61]:
#method 44
ruhan.power(1,2)

1

In [63]:
#method 45
ruhan.hsplit(t,3)

[array([[3],
        [6],
        [9]]),
 array([[4],
        [5],
        [4]]),
 array([[4],
        [5],
        [5]])]

In [64]:
#method 46
ruhan.vsplit(t,3)

[array([[3, 4, 4]]), array([[6, 5, 5]]), array([[9, 4, 5]])]

In [65]:
#method 47
ruhan.absolute(t)

array([[3, 4, 4],
       [6, 5, 5],
       [9, 4, 5]])

In [66]:
#method 48
ruhan.prod(t)

1296000

In [67]:
#method 49
ruhan.std(t)

1.632993161855452

In [68]:
#method 50
ruhan.var(t)

2.6666666666666665